//old one dont read this 

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatNumber, formatDateLong, formatDateTime } from "@/lib/utils";
import type {
  DisbursementRecord,
  ExpenseFilters,
  ExpenseKpis,
  ExpenseByCategory,
  ExpenseByEmployee,
  ExpenseByDivision,
  ExportFormat,
} from "../type";

// Extend jsPDF type to include autoTable
declare module "jspdf" {
  interface jsPDF {
    lastAutoTable?: {
      finalY: number;
    };
  }
}

type ExportOptions = {
  records: DisbursementRecord[];
  filters: ExpenseFilters;
  kpis: ExpenseKpis;
  expensesByCategory: ExpenseByCategory[];
  expensesByEmployee: ExpenseByEmployee[];
  expensesByDivision: ExpenseByDivision[];
  format: ExportFormat;
  groupBy?: "coa" | "division";
  userName?: string;
};

export async function exportToPDF2({
  records,
  filters,
  kpis,
  expensesByCategory,
  expensesByEmployee,
  expensesByDivision,
  format,
  groupBy = "coa",
  userName = "User",
}: ExportOptions) {
  const doc = new jsPDF("landscape");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let currentY = 20;

  // Helper to add new page
  const addPageIfNeeded = (requiredSpace: number = 30) => {
    if (currentY + requiredSpace > pageHeight - 20) {
      doc.addPage();
      currentY = 20;
      addHeader();
    }
  };

  // Header on every page
  const addHeader = () => {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("DISBURSEMENT REPORT", pageWidth / 2, 15, { align: "center" });

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const reportType =
      format === "summary" ? "Summary Report" : "Detailed Report";
    const dateRange = `${formatDateLong(new Date(filters.dateFrom))} - ${formatDateLong(new Date(filters.dateTo))}`;
    const generatedBy = `Generated By: ${userName}`;
    const generatedOn = `Generated On: ${formatDateTime(new Date())}`;

    doc.text(`Report Type: ${reportType}`, 15, 25);
    doc.text(`Date Range: ${dateRange}`, 15, 30);
    doc.text(generatedBy, pageWidth - 15, 25, { align: "right" });
    doc.text(generatedOn, pageWidth - 15, 30, { align: "right" });

    currentY = 35;
  };

  addHeader();

  // Helper to output safe currency text (avoid symbol/font issues in PDF)
  const safeCurrency = (amt: number | string | null | undefined) => {
    const n = typeof amt === "number" ? amt : parseFloat(String(amt ?? "0"));
    // format with locale grouping/decimals but prefix with ASCII currency code to avoid glyph issues
    return `PHP ${formatNumber(Number.isFinite(n) ? n : 0)}`;
  };

  // Executive Summary
  addPageIfNeeded(80);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE SUMMARY", 15, currentY);
  currentY += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryData = [
    ["Total Disbursement:", safeCurrency(kpis.totalDisbursementAmount)],
    ["Total Paid Amount:", safeCurrency(kpis.totalPaidAmount)],
    ["Outstanding Balance:", safeCurrency(kpis.outstandingBalance)],
    ["Total Transactions:", kpis.totalTransactions.toString()],
    ["Posted Transactions:", kpis.postedTransactions.toString()],
    ["Pending Approvals:", kpis.pendingApprovalsCount.toString()],
    ["Tax Withholding Impact:", safeCurrency(kpis.taxWithholdingImpact)],
  ];

  autoTable(doc, {
    startY: currentY,
    head: [],
    body: summaryData,
    theme: "plain",
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60 },
      1: { cellWidth: 60 },
    },
  });

  currentY =
    doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
      ? doc.lastAutoTable.finalY + 10
      : currentY + 10;

  // Visual Insights (Summary only)
  if (format === "summary") {
    addPageIfNeeded(60);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("TOP CATEGORIES", 15, currentY);
    currentY += 8;

    const topCategories = expensesByCategory.slice(0, 10);
    autoTable(doc, {
      startY: currentY,
      head: [["COA Title", "Total Amount", "% Share"]],
      body: topCategories.map((cat) => [
        cat.coaTitle,
        safeCurrency(cat.totalAmount),
        `${cat.percentShare.toFixed(1)}%`,
      ]),
      theme: "striped",
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246] },
    });

    currentY =
      doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
        ? doc.lastAutoTable.finalY + 10
        : currentY + 10;

    addPageIfNeeded(60);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("TOP EMPLOYEES", 15, currentY);
    currentY += 8;

    const topEmployees = expensesByEmployee.slice(0, 10);
    autoTable(doc, {
      startY: currentY,
      head: [["Employee Name", "Total Amount", "Transactions", "% Share"]],
      body: topEmployees.map((emp) => [
        emp.payeeName,
        safeCurrency(emp.totalAmount),
        emp.transactionCount.toString(),
        `${emp.percentShare.toFixed(1)}%`,
      ]),
      theme: "striped",
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246] },
    });

    currentY =
      doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
        ? doc.lastAutoTable.finalY + 10
        : currentY + 10;

    addPageIfNeeded(60);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("DIVISION SPENDING", 15, currentY);
    currentY += 8;

    const topDivisions = expensesByDivision.slice(0, 10);
    autoTable(doc, {
      startY: currentY,
      head: [["Division Name", "Total Amount", "Transactions", "% Share"]],
      body: topDivisions.map((div) => [
        div.divisionName,
        safeCurrency(div.totalAmount),
        div.transactionCount.toString(),
        `${div.percentShare.toFixed(1)}%`,
      ]),
      theme: "striped",
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246] },
    });

    currentY =
      doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
        ? doc.lastAutoTable.finalY + 10
        : currentY + 10;
  }

  // Main Table - Grouped by COA or Division
  addPageIfNeeded(40);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  const groupByLabel = groupBy === "division" ? "DIVISION" : "CHART OF ACCOUNT";
  doc.text(`DISBURSEMENT TRANSACTIONS (Grouped by ${groupByLabel})`, 15, currentY);
  currentY += 8;

  // Group records by COA or Division
  const groupedRecords = new Map<string, DisbursementRecord[]>();
  records.forEach((record) => {
    const groupKey =
      groupBy === "division" ? record.divisionName : record.coaTitle;
    if (!groupedRecords.has(groupKey)) {
      groupedRecords.set(groupKey, []);
    }
    groupedRecords.get(groupKey)!.push(record);
  });

  // Sort groups by total amount
  const sortedGroups = Array.from(groupedRecords.entries())
    .map(([groupTitle, groupRecords]) => ({
      groupTitle,
      records: groupRecords,
      total: groupRecords.reduce((sum, r) => sum + r.lineAmount, 0),
    }))
    .sort((a, b) => b.total - a.total);

  // Render each group
  sortedGroups.forEach((group) => {
    addPageIfNeeded(40);

    // Group header
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setFillColor(240, 240, 240);
    doc.rect(15, currentY - 5, pageWidth - 30, 8, "F");
    const groupLabel = groupBy === "division" ? "Division" : "COA";
    doc.text(`${groupLabel}: ${group.groupTitle}`, 20, currentY);
    doc.text(`Total: ${safeCurrency(group.total)}`, pageWidth - 20, currentY, {
      align: "right",
    });
    currentY += 10;

    // Group table
    if (format === "summary") {
      autoTable(doc, {
        startY: currentY,
        head: [["Ref No", "Date", "Payee", "Description", "Amount", "Status"]],
        body: group.records.map((r) => [
          r.docNo,
          formatDateLong(new Date(r.transactionDate)),
          r.payeeName,
          r.lineRemarks || "-",
          safeCurrency(r.lineAmount),
          r.isPosted === 1 ? "Posted" : "Draft",
        ]),
        theme: "striped",
        styles: { fontSize: 8 },
        headStyles: { fillColor: [59, 130, 246], fontSize: 9 },
        columnStyles: {
          4: { halign: "right" },
        },
      });
    } else {
      // Detailed format with all fields
      group.records.forEach((record) => {
        addPageIfNeeded(80);

        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(`Transaction: ${record.docNo}`, 20, currentY);
        currentY += 8;

        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        const detailsData = [
          ["Doc No:", record.docNo],
          ["Transaction Type:", record.transactionTypeName],
          ["Payee:", record.payeeName],
          [groupBy === "division" ? "COA:" : "Division:", groupBy === "division" ? record.coaTitle : record.divisionName],
          ["Reference No:", record.referenceNo || "-"],
          ["Total Amount:", safeCurrency(record.totalAmount)],
          ["Paid Amount:", safeCurrency(record.paidAmount)],
          ["Line Amount:", safeCurrency(record.lineAmount)],
          [
            "Transaction Date:",
            formatDateLong(new Date(record.transactionDate)),
          ],
          ["Payable Date:", formatDateLong(new Date(record.lineDate))],
          ["Status:", record.isPosted === 1 ? "Posted" : "Draft"],
          ["Encoder:", record.encoderName],
          ["Approver:", record.approverName || "Pending"],
          ["Posted By:", record.postedByName || "Not Posted"],
          [
            "Created:",
            formatDateTime(new Date(record.disbursementDateCreated)),
          ],
          [
            "Updated:",
            formatDateTime(new Date(record.disbursementDateUpdated)),
          ],
          ["Remarks:", record.lineRemarks || "-"],
        ];

        autoTable(doc, {
          startY: currentY,
          body: detailsData,
          theme: "plain",
          styles: { fontSize: 8 },
          columnStyles: {
            0: { fontStyle: "bold", cellWidth: 40 },
          },
        });

        currentY =
          doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
            ? doc.lastAutoTable.finalY + 8
            : currentY + 8;
      });
    }

    currentY =
      doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
        ? doc.lastAutoTable.finalY + 8
        : currentY + 8;

    // Subtotal
    currentY =
      doc.lastAutoTable && typeof doc.lastAutoTable.finalY === "number"
        ? doc.lastAutoTable.finalY + 5
        : currentY + 5;
    doc.setFont("helvetica", "bold");
    doc.text(
      `Subtotal - ${group.groupTitle}: ${safeCurrency(group.total)}`,
      pageWidth - 20,
      currentY,
      { align: "right" },
    );
    currentY += 10;
  });

  // Grand Total
  addPageIfNeeded(20);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(
    `GRAND TOTAL: ${safeCurrency(kpis.totalDisbursementAmount)}`,
    pageWidth / 2,
    currentY,
    { align: "center" },
  );

  // Footer on last page
  currentY = pageHeight - 30;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Prepared by: _______________________", 20, currentY);
  doc.text("Approved by: _______________________", pageWidth - 80, currentY);

  // Add page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, {
      align: "center",
    });
  }

  // Save PDF
  const fileName = `Disbursement_Report_${format}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}
